apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: multiplyapp
  name: multiplyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiplyapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: multiplyapp
    spec:
      containers:
        - image: energyuktc/multiplyapp:latest
          name: multiplyapp
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: multiplyapp
  name: multiplyapp
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: multiplyapp
  type: LoadBalancer
status:
  loadBalancer: {}
