VERSION ?= $(shell git rev-parse HEAD)
APP     ?= multiplyapp
IMAGE   ?= energyuktc/multiplyapp/$(APP):$(VERSION)

all: build push

build:

   docker build -t $(IMAGE) .

run:

   docker run -p 8080:8080 $(IMAGE)

push:

   docker push $(IMAGE)

k8/install:

   kubectl apply -f deployment.yaml

k8/delete:

   kubectl delete -f deployment.yaml